"""
Fine-tune DocRes Restormer for dewarping only.
Uses synthetic dataset generated by generate_dewarp_dataset.py
"""
import os, sys, json, time, glob, random
import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from pathlib import Path

# Setup
DOCRES_DIR = Path("/home/wahyu/DocRes")
sys.path.insert(0, str(DOCRES_DIR))
from models import restormer_arch
from utils import convert_state_dict

DATA_DIR = Path("/home/wahyu/docai/datasets/train_dewarp_v1")
DEVICE = torch.device("cuda")
BATCH_SIZE = 4
LR = 1e-4
NUM_EPOCHS = 50
IM_SIZE = 512
TOTAL_IMGS = 10000

class DewarpDataset(Dataset):
    def __init__(self, data_dir, split="train", ratio=0.9):
        self.data_dir = data_dir
        json_path = data_dir / "train.json"
        with open(json_path) as f:
            all_data = json.load(f)["data"]
        random.shuffle(all_data)
        split_idx = int(len(all_data) * ratio)
        self.data = all_data[:split_idx] if split == "train" else all_data[split_idx:]
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        item = self.data[idx]
        in_im = cv2.imread(str(self.data_dir / item["in_path"]))
        bm = np.load(str(self.data_dir / item["bm_path"]))
        mask = cv2.imread(str(self.data_dir / item["mask_path"]), 0)
        
        # Resize
        h, w = in_im.shape[:2]
        in_im = cv2.resize(in_im, (IM_SIZE, IM_SIZE))
        mask = cv2.resize(mask, (IM_SIZE, IM_SIZE))
        bm = cv2.resize(bm, (IM_SIZE, IM_SIZE))
        
        # Normalize
        in_t = torch.from_numpy(in_im.transpose(2,0,1).astype(np.float32) / 255.0)
        mask_t = torch.from_numpy((mask / 255.0).astype(np.float32)).unsqueeze(0)
        
        # BM: [0,1] range, as-is
        bm_t = torch.from_numpy(bm.transpose(2,0,1).astype(np.float32))
        
        # Create DTSPrompt for dewarping: base_coord + mask
        base_coord0 = np.tile(np.arange(IM_SIZE).reshape(IM_SIZE,1), (1,IM_SIZE)).astype(np.float32) / IM_SIZE
        base_coord1 = np.tile(np.arange(IM_SIZE).reshape(1,IM_SIZE), (IM_SIZE,1)).astype(np.float32) / IM_SIZE
        coord = np.stack([base_coord1, base_coord0], axis=-1)
        prompt = np.concatenate([coord, mask_t.permute(1,2,0).numpy()], axis=-1).transpose(2,0,1).astype(np.float32)
        prompt_t = torch.from_numpy(prompt)
        
        # Input: concat image + prompt
        x = torch.cat([in_t, prompt_t], dim=0)
        
        # GT: BM (2 channels)
        y = bm_t
        
        return x, y

def grid_loss(pred, target, mask=None):
    """L1 + gradient loss on flow field."""
    loss_l1 = F.l1_loss(pred, target, reduction="none")
    if mask is not None:
        loss_l1 = loss_l1 * mask.repeat(1, 2, 1, 1)
    l1 = loss_l1.mean()
    
    # Gradient loss (smoothness)
    dx_pred = torch.abs(pred[:, :, :, :-1] - pred[:, :, :, 1:])
    dy_pred = torch.abs(pred[:, :, :-1, :] - pred[:, :, 1:, :])
    grad_loss = dx_pred.mean() + dy_pred.mean()
    
    return l1 + 0.1 * grad_loss

# Model
model = restormer_arch.Restormer(
    inp_channels=6, out_channels=3, dim=48,
    num_blocks=[2,3,3,4], num_refinement_blocks=4,
    heads=[1,2,4,8], ffn_expansion_factor=2.66,
    bias=False, LayerNorm_type="WithBias", dual_pixel_task=True
)

# Load pretrained (general model)
print("Loading pretrained checkpoint...")
state = convert_state_dict(torch.load(
    str(DOCRES_DIR / "checkpoints" / "docres.pkl"), map_location="cpu"
)["model_state"])
model.load_state_dict(state, strict=False)
model.to(DEVICE)
print(f"Params: {sum(p.numel() for p in model.parameters())/1e6:.1f}M")

# Dataset
print("Loading dataset...")
dataset = DewarpDataset(DATA_DIR, "train")
val_dataset = DewarpDataset(DATA_DIR, "val")
loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=4, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, num_workers=4, pin_memory=True)
print(f"Train: {len(dataset)}, Val: {len(val_dataset)}")

optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=NUM_EPOCHS)
best_val = float("inf")

print("Starting training...")
for epoch in range(NUM_EPOCHS):
    model.train()
    train_loss = 0
    for x, y in loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        pred = model(x)
        # pred has 3 channels (RGB residual for other tasks), we take first 2 for flow
        pred_flow = pred[:, :2]
        loss = grid_loss(pred_flow, y)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        train_loss += loss.item()
    
    # Validation
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for x, y in val_loader:
            x, y = x.to(DEVICE), y.to(DEVICE)
            pred = model(x)
            pred_flow = pred[:, :2]
            val_loss += grid_loss(pred_flow, y).item()
    
    train_loss /= len(loader)
    val_loss /= len(val_loader)
    scheduler.step()
    
    print(f"Epoch {epoch+1}/{NUM_EPOCHS} | train: {train_loss:.6f} | val: {val_loss:.6f} | lr: {scheduler.get_last_lr()[0]:.2e}")
    
    if val_loss < best_val:
        best_val = val_loss
        torch.save({
            "model_state": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "epoch": epoch,
            "val_loss": val_loss,
        }, "/home/wahyu/docai/checkpoints/dewarp_finetune.pth")
        print(f"  Saved best model (val_loss: {val_loss:.6f})")

print("Training complete!")
